services:
  redis:
    image: redis:7.4.1-alpine3.20
    ports:
      - "127.0.0.1:${REDIS_HOST_PORT}:6379"
    volumes:
      - redis-data:/data
    restart: always
  server:
    build: ./server
    ports:
      - "127.0.0.1:${SERVER_HOST_PORT}:8080"
    environment:
      REDIS_CONNECTION_STRING: "redis://default@redis:6379"
    restart: always
  web:
    build: ./web
    ports:
      - "127.0.0.1:${WEB_APP_HOST_PORT}:80"
    restart: always

volumes:
  redis-data:
