# fly.toml app configuration file generated for ocppplayground on 2024-10-19T19:08:00+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ocppplayground'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [services.concurrency]
    type = "connections"
    hard_limit = 15
    soft_limit = 10

[[vm]]
  size = 'shared-cpu-1x'
